[tool.poetry]
name = "kp-2"
version = "0.1.0"
description = ""
authors = ["Olesya <flomaster597@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
black = "^26.5.1"
isort = "^9.0.1"
flake8 = "^7.4.1"
mypy = "^2.3.1"
pandas = "^3.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
